import gradio as gr
import numpy as np
import random
import torch
from datetime import datetime
from PIL import Image
import os
import sys
import logging

# Add the app directory to path for sensenova_u1 imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from transformers import AutoConfig, AutoModel, AutoTokenizer
import sensenova_u1
from sensenova_u1 import check_checkpoint_compatibility
from sensenova_u1.utils import DEFAULT_IMAGE_PATCH_SIZE, InferenceProfiler

# Enable verbose logging
logging.getLogger("huggingface_hub").setLevel(logging.INFO)
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["TQDM_POSITION"] = "0"

# Configuration
# Resolves the local model directory generated by download.js in the project root
local_model_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "models", "SenseNova-U1-8B-MoT")
MODEL_PATH = local_model_path if os.path.exists(local_model_path) else "sensenova/SenseNova-U1-8B-MoT"

dtype = torch.bfloat16
device = "cuda" if torch.cuda.is_available() else "cpu"
MAX_SEED = np.iinfo(np.int32).max
MAX_IMAGE_SIZE = 2048

# Supported resolution buckets
SUPPORTED_RESOLUTIONS = {
    "1:1 (2048x2048)": (2048, 2048),
    "16:9 (2720x1536)": (2720, 1536),
    "9:16 (1536x2720)": (1536, 2720),
    "3:2 (2496x1664)": (2496, 1664),
    "2:3 (1664x2496)": (1664, 2496),
    "4:3 (2368x1760)": (2368, 1760),
    "3:4 (1760x2368)": (1760, 2368),
    "2:1 (2880x1440)": (2880, 1440),
    "1:2 (1440x2880)": (1440, 2880),
    "3:1 (3456x1152)": (3456, 1152),
    "1:3 (1152x3456)": (1152, 3456),
}

NORM_MEAN = (0.5, 0.5, 0.5)
NORM_STD = (0.5, 0.5, 0.5)

# Global engine instances
t2i_engine = None
edit_engine = None

def _denorm(x: torch.Tensor) -> torch.Tensor:
    """Invert normalization back to [0, 1]."""
    mean = torch.tensor(NORM_MEAN, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
    std = torch.tensor(NORM_STD, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
    return (x * std + mean).clamp(0, 1)

def _to_pil(batch: torch.Tensor) -> list:
    """Convert tensor to PIL images."""
    arr = _denorm(batch.float()).permute(0, 2, 3, 1).cpu().numpy()
    arr = (arr * 255.0).round().astype(np.uint8)
    return [Image.fromarray(a) for a in arr]

def format_size(size_bytes):
    """Format bytes to human-readable size."""
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.2f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.2f} PB"

def save_image(image):
    """Save generated image to output folder with unique name."""
    output_folder = "output"
    os.makedirs(output_folder, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"sensenova_u1_{timestamp}.png"
    filepath = os.path.join(output_folder, filename)
    image.save(filepath)
    return filepath

def get_t2i_engine():
    """Lazy-load the T2I engine."""
    global t2i_engine
    if t2i_engine is None:
        print("\n🔄 Loading SenseNova-U1 T2I engine...")
        print(f"   Model Path: {MODEL_PATH}")
        print("   Device: cuda")
        print("   Dtype: bfloat16\n")

        config = AutoConfig.from_pretrained(MODEL_PATH)
        check_checkpoint_compatibility(config)
        tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
        model = AutoModel.from_pretrained(MODEL_PATH, config=config, torch_dtype=dtype).to(device).eval()

        t2i_engine = {
            "model": model,
            "tokenizer": tokenizer,
            "last_think_text": ""
        }
        print("✅ T2I engine loaded successfully!\n")
    return t2i_engine

def get_edit_engine():
    """Lazy-load the image editing engine."""
    global edit_engine
    if edit_engine is None:
        print("\n🔄 Loading SenseNova-U1 Image Editing engine...")
        print(f"   Model Path: {MODEL_PATH}")
        print("   Device: cuda")
        print("   Dtype: bfloat16\n")

        config = AutoConfig.from_pretrained(MODEL_PATH)
        check_checkpoint_compatibility(config)
        tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
        model = AutoModel.from_pretrained(MODEL_PATH, config=config, torch_dtype=dtype).to(device).eval()

        edit_engine = {
            "model": model,
            "tokenizer": tokenizer
        }
        print("✅ Image Editing engine loaded successfully!\n")
    return edit_engine

def text_to_image(prompt, resolution_key, seed, randomize_seed, num_inference_steps, cfg_scale, cfg_norm, timestep_shift, think_mode):
    """Generate image from text prompt."""
    if not prompt or not prompt.strip():
        raise gr.Error("Please enter a prompt.")

    engine = get_t2i_engine()

    if randomize_seed:
        seed = random.randint(0, MAX_SEED)

    width, height = SUPPORTED_RESOLUTIONS.get(resolution_key, (2048, 2048))

    print(f"\n🎨 Generating image...")
    print(f"   Prompt: {prompt[:80]}...")
    print(f"   Resolution: {width}x{height}")
    print(f"   Steps: {num_inference_steps}")
    print(f"   CFG Scale: {cfg_scale}")
    print(f"   Seed: {seed}")
    print(f"   Think Mode: {think_mode}\n")

    try:
        with torch.inference_mode():
            out = engine["model"].t2i_generate(
                engine["tokenizer"],
                prompt,
                image_size=(width, height),
                cfg_scale=cfg_scale,
                cfg_norm=cfg_norm,
                timestep_shift=timestep_shift,
                cfg_interval=(0.0, 1.0),
                num_steps=num_inference_steps,
                batch_size=1,
                seed=seed,
                think_mode=think_mode,
            )

            if think_mode:
                tensor, think_text = out
                engine["last_think_text"] = think_text
            else:
                tensor = out
                engine["last_think_text"] = ""

            images = _to_pil(tensor)
            image = images[0]
    except Exception as e:
        raise gr.Error(f"Generation failed: {str(e)}")

    saved_path = save_image(image)
    print(f"✅ Image saved to: {saved_path}\n")

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    think_output = engine["last_think_text"] if think_mode else ""
    return image, seed, saved_path, think_output

def image_to_image(input_image, prompt, seed, randomize_seed, num_inference_steps, cfg_scale, img_cfg_scale, cfg_norm, timestep_shift, think_mode, target_pixels):
    """Edit image based on prompt."""
    if input_image is None:
        raise gr.Error("Please upload an input image.")
    if not prompt or not prompt.strip():
        raise gr.Error("Please enter an edit prompt.")

    engine = get_edit_engine()

    if randomize_seed:
        seed = random.randint(0, MAX_SEED)

    if not isinstance(input_image, Image.Image):
        input_image = Image.fromarray(input_image).convert("RGB")
    else:
        input_image = input_image.convert("RGB")

    from sensenova_u1.models.neo_unify.utils import smart_resize
    resized_h, resized_w = smart_resize(
        height=input_image.height,
        width=input_image.width,
        factor=DEFAULT_IMAGE_PATCH_SIZE,
        min_pixels=target_pixels,
        max_pixels=target_pixels,
    )
    if (resized_w, resized_h) != input_image.size:
        input_image = input_image.resize((resized_w, resized_h), Image.LANCZOS)

    print(f"\n🖼️ Editing image...")
    print(f"   Prompt: {prompt[:80]}...")
    print(f"   Input size: {input_image.size}")
    print(f"   Steps: {num_inference_steps}")
    print(f"   CFG Scale: {cfg_scale}")
    print(f"   Image CFG: {img_cfg_scale}")
    print(f"   Seed: {seed}\n")

    try:
        with torch.inference_mode():
            output = engine["model"].it2i_generate(
                engine["tokenizer"],
                prompt,
                [input_image],
                image_size=(resized_w, resized_h),
                cfg_scale=cfg_scale,
                img_cfg_scale=img_cfg_scale,
                cfg_norm=cfg_norm,
                timestep_shift=timestep_shift,
                cfg_interval=(0.0, 1.0),
                num_steps=num_inference_steps,
                batch_size=1,
                think_mode=think_mode,
                seed=seed,
            )

            if think_mode:
                images, think_text = output
                images = _to_pil(images)
            else:
                images = _to_pil(output)
                think_text = ""

            image = images[0]
    except Exception as e:
        raise gr.Error(f"Editing failed: {str(e)}")

    saved_path = save_image(image)
    print(f"✅ Edited image saved to: {saved_path}\n")

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return image, seed, saved_path, think_text

css = """
.container { max-width: 1400px; margin: auto; }
.tab-content { padding: 10px; }
.think-box { 
    background: #1a1a2e; 
    color: #eee; 
    padding: 15px; 
    border-radius: 8px; 
    font-family: monospace;
    white-space: pre-wrap;
    max-height: 300px;
    overflow-y: auto;
}
"""

with gr.Blocks(title="SenseNova-U1 Image", css=css) as demo:
    gr.Markdown("""
    # 🎨 SenseNova-U1 Image Generator & Editor

    Powered by **SenseNova-U1-8B-MoT** — a native unified multimodal model with NEO-Unify architecture.
    Supports high-resolution text-to-image generation and image-to-image editing up to 2048x2048.
    """)

    with gr.Tabs():
        with gr.TabItem("🎨 Text to Image"):
            with gr.Row():
                with gr.Column(scale=1):
                    t2i_prompt = gr.Textbox(label="Prompt", placeholder="Describe the image you want to generate...", lines=4)
                    with gr.Accordion("⚙️ Advanced Settings", open=False):
                        t2i_resolution = gr.Dropdown(label="Resolution", choices=list(SUPPORTED_RESOLUTIONS.keys()), value="1:1 (2048x2048)")
                        with gr.Row():
                            t2i_steps = gr.Slider(label="Inference Steps", minimum=10, maximum=100, step=1, value=50)
                            t2i_cfg = gr.Slider(label="CFG Scale", minimum=0.1, maximum=20.0, step=0.1, value=4.0)
                        with gr.Row():
                            t2i_cfg_norm = gr.Dropdown(label="CFG Norm", choices=["none", "global", "channel", "cfg_zero_star"], value="none")
                            t2i_shift = gr.Slider(label="Timestep Shift", minimum=0.5, maximum=10.0, step=0.1, value=3.0)
                        with gr.Row():
                            t2i_seed = gr.Number(label="Seed", value=42, precision=0, step=1)
                            t2i_randomize = gr.Checkbox(label="Randomize Seed", value=True)
                        t2i_think = gr.Checkbox(label="🧠 Think Mode (Reasoning)", value=False, info="Enable chain-of-thought reasoning before generation")
                    t2i_generate = gr.Button("✨ Generate Image", variant="primary", size="lg")

                with gr.Column(scale=1):
                    t2i_output = gr.Image(label="Generated Image", type="pil", interactive=False, height=500)
                    with gr.Row():
                        t2i_seed_out = gr.Number(label="Used Seed", interactive=False)
                        t2i_path = gr.Textbox(label="Saved Path", interactive=False)
                    t2i_think_output = gr.Textbox(label="🧠 Reasoning Output", lines=6, interactive=False, visible=False)

            t2i_generate.click(
                fn=text_to_image,
                inputs=[t2i_prompt, t2i_resolution, t2i_seed, t2i_randomize, t2i_steps, t2i_cfg, t2i_cfg_norm, t2i_shift, t2i_think],
                outputs=[t2i_output, t2i_seed_out, t2i_path, t2i_think_output]
            )

        with gr.TabItem("🖼️ Image to Image"):
            with gr.Row():
                with gr.Column(scale=1):
                    i2i_input = gr.Image(label="Input Image", type="pil", height=300)
                    i2i_prompt = gr.Textbox(label="Edit Prompt", placeholder="Describe how you want to modify the image...", lines=3)
                    with gr.Accordion("⚙️ Advanced Settings", open=False):
                        with gr.Row():
                            i2i_steps = gr.Slider(label="Inference Steps", minimum=10, maximum=100, step=1, value=50)
                            i2i_cfg = gr.Slider(label="Text CFG Scale", minimum=0.1, maximum=20.0, step=0.1, value=4.0)
                        with gr.Row():
                            i2i_img_cfg = gr.Slider(label="Image CFG Scale", minimum=0.1, maximum=5.0, step=0.1, value=1.0, info="1.0 = image CFG disabled")
                            i2i_cfg_norm = gr.Dropdown(label="CFG Norm", choices=["none", "global", "channel"], value="none")
                        with gr.Row():
                            i2i_shift = gr.Slider(label="Timestep Shift", minimum=0.5, maximum=10.0, step=0.1, value=3.0)
                            i2i_target_pixels = gr.Slider(label="Target Pixels", minimum=512*512, maximum=2048*2048, step=1024, value=2048*2048, info="Output resolution target")
                        with gr.Row():
                            i2i_seed = gr.Number(label="Seed", value=42, precision=0, step=1)
                            i2i_randomize = gr.Checkbox(label="Randomize Seed", value=True)
                        i2i_think = gr.Checkbox(label="🧠 Think Mode (Reasoning)", value=False, info="Enable chain-of-thought reasoning before editing")
                    i2i_generate = gr.Button("✨ Edit Image", variant="primary", size="lg")

                with gr.Column(scale=1):
                    i2i_output = gr.Image(label="Edited Image", type="pil", interactive=False, height=500)
                    with gr.Row():
                        i2i_seed_out = gr.Number(label="Used Seed", interactive=False)
                        i2i_path = gr.Textbox(label="Saved Path", interactive=False)
                    i2i_think_output = gr.Textbox(label="🧠 Reasoning Output", lines=6, interactive=False, visible=False)

            i2i_generate.click(
                fn=image_to_image,
                inputs=[i2i_input, i2i_prompt, i2i_seed, i2i_randomize, i2i_steps, i2i_cfg, i2i_img_cfg, i2i_cfg_norm, i2i_shift, i2i_think, i2i_target_pixels],
                outputs=[i2i_output, i2i_seed_out, i2i_path, i2i_think_output]
            )

# Launch with dynamic port
port_env = os.environ.get("PORT", "")
server_port = int(port_env) if port_env.isdigit() else 7860

demo.launch(
    server_name="127.0.0.1",
    server_port=server_port,
    show_error=True
)